config/routes.rb
Rails.application.routes.draw do
  root to: 'properties#index'
  resources :properties
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
  has_many :stations
  #accepts_nested_attributes_for :stations
  accepts_nested_attributes_for :stations, :allow_destroy => true
end

app/models/station.rb
class Station < ApplicationRecord
  belongs_to :property
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
    1.times { @property.stations.build }
  end

  # GET /properties/1/edit
  def edit
    @property.stations.build
  end

  # POST /properties
  # POST /properties.json
  def create
    	@property = Property.new(property_params)
    	if params[:back]
        render :new
      else
  	    if @property.save
  	      redirect_to properties_path, notice: "'Property was successfully created!"
  	    else
  	      render :new
  	    end
  	  end
    end
  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_property
  @property = Property.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def property_params
  params.require(:property).permit(:property_name, :rent, :address, :age, :remark, stations_attributes: [:id, :line, :station, :time])
  end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MofMof</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/properties/_form.html.erb
<%= form_with(model: @property, local: true) do |form| %>
<% v = 0 %>
<% @property.stations.each do |x| %>
<% if x.station.present? %>
  <% v += 1 %>
 <% end %>
<% end %>
<h3>This property has <%=v%> nearest station(s)</h3>

  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<hr>

<h2>Register property</h2>
  <div class="field">
      <%= form.label :property_name, "Property name"  %>
      <%= form.text_field :property_name %>
    </div>

    <div class="field">
      <%= form.label :rent, "Rent"  %>
      <%= form.number_field :rent %>
    </div>

    <div class="field">
      <%= form.label :address, "Address"%>
      <%= form.text_field :address %>
    </div>

    <div class="field">
      <%= form.label :age, "Building's age"%>
      <%= form.number_field :age %>
    </div>

    <div class="field">
      <%= form.label :remark, "Remarks"%>
      <%= form.text_area :remark %>
    </div>

    <hr>
      <% n = 0 %>
  <%= form.fields_for :stations do |g| %>
      <h2>Nearest station <%= n += 1 %></h2>
      <div class="field">
        <div>
          <%= g.label :line, "Line name"%>
        </div>
        <div>
          <%= g.text_field :line %>
        </div>
      </div>

      <div class="field">
        <div>
          <%= g.label :station, "Station name"  %>
        </div>
        <div>
          <%= g.text_field :station %>
        </div>
      </div>

      <div class="field">
        <div>
          <%= g.label :time, "By walk"  %>
        </div>
        <div>
         <%= g.text_field :time %>min
        </div>
      </div>
       <% end %>

       <div class="actions">
      <%= form.submit value:"Register"%>
      </div>
      <% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Properties list</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Rent</th>
      <th>Address</th>
      <th>Age</th>
      <th>Remarks</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.property_name %></td>
        <td><%= property.rent %></td>
        <td><%= property.address %></td>
        <td><%= property.age %></td>
        <td><%= property.remark %></td>
        <td><%= link_to 'See', property_path(property.id) %></td>
        <td><%= link_to "Edit", edit_property_path(property.id) %></td>
        <td><%= link_to 'Delete', property_path(property.id), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<h1>Property Details</h1>
<br>

<p id="notice"><%= notice %></p>

<% n = 0 %>
<% @property.stations.each do |x| %>
	<% if x.station.present? %>
		<% n += 1 %>
	<% end %>
<% end %>
<h3>This property has <%=n %> nearest station(s)</h3>

<hr>

<p>
  <strong>Property's name:</strong>
<%= @property.property_name %>
</p>

<p>
 <strong>Rent:</strong>
 <%= @property.rent %>
</p>

  <p>
 <strong>Address:</strong>
 <%= @property.address %>
</p>

<p>
 <strong>Building's age:</strong>
 <%= @property.age %>
</p>

<p>
 <strong>Remarks:</strong>
 <%= @property.remark %>
</p>

<hr>
 <div>
<%n = 0%>
<% @property.stations.each do |station|%>
    <% if station.station.present? %>
    <h2>Nearest Station<%= n += 1 %></h2>

  <p>
    <strong>Line:</strong>
    <%= station.line %>
  </p>

  <p>
    <strong> Station:</strong>
    <%= station.station %>
  </p>
  <p>
    <strong>By walk:</strong>
    <%= station.time %>
  </p>
  <% end %>
  <% end %>
</div>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>